### ISSUE TITLE
レスポンシブ対応

### ISSUE THREAD

**Issue by yumekiti** [yumekiti/OC_Trial_Lesson#5]
## 概要
レスポンシブwebデザインに対応させる

## タスク
- [x] style.cssの変更

**Comment by yumekiti** [comment]
こんな感じで実装できそう

```css
@media(max-width: 480px){
  .grid {
    grid-template-columns: 6fr;
  }
}

```
